config/routes.rb
Snookerclub::Application.routes.draw do
  match "/auth/:provider/callback" => "sessions#callback"
  match "/auth/failure" => "sessions#failure"
  match "/logout" => "sessions#destroy", :as => :logout

  resources :plays

  root to: 'home#index'

end

app/models/account.rb
# coding: utf-8
class Account < ActiveRecord::Base
  has_many :plays
  attr_accessible :provider, :uid, :name, :screen_name, :image, :token, :secret

  private

  #---------------------------#
  # self.create_with_omniauth #
  #---------------------------#
  def self.create_with_omniauth( auth )
    account = Account.new
    account[:provider] = auth["provider"]
    account[:uid] = auth["uid"]

    unless auth["info"].blank?
      account[:name] = auth["info"]["name"]
      account[:screen_name] = auth["info"]["nickname"]
      account[:image] = auth["info"]["image"]
    end
    
    unless auth["credentials"].blank?
      account.token = auth['credentials']['token']
      account.secret = auth['credentials']['secret']
    end

    account.save

    return account
  end

end

app/models/play.rb
class Play < ActiveRecord::Base
  belongs_to :account
  attr_accessible :ends_at, :note, :starts_at, :table_id

  scope :current, lambda {|time| where("starts_at <= ? AND (ends_at IS NULL OR ends_at > ?)", time, time) }

  def username
    account.try(:name) || I18n.t('customer')
  end
end

app/controllers/application_controller.rb
# coding: utf-8
class ApplicationController < ActionController::Base

  protect_from_forgery
  
  # httpsリダイレクト
  #before_filter :ssl_redirect if Rails.env.production?
  
  # 未ログインリダイレクト
  #before_filter :authorize
  
  # セッション有効期限延長
  before_filter :reset_session_expires

  private
  
  #--------------#
  # ssl_redirect #
  #--------------#
  # httpsへリダイレクト(Production環境のみ)
  def ssl_redirect
    unless request.env["HTTP_X_FORWARDED_PROTO"].to_s == "https"
      request.env["HTTP_X_FORWARDED_PROTO"] = "https"
      
      redirect_to request.url and return
    end
  end
  
  #-----------#
  # authorize #
  #-----------#
  # ログイン認証
  def authorize
    # セッション／トップコントローラ以外で
    if params[:controller] != "sessions" and params[:controller] != "home"
      # 未ログインであればルートヘリダイレクト
      if session[:account_id].blank?
        redirect_to :root and return
      end
    end
  end
  
  #-----------------------#
  # reset_session_expires #
  #-----------------------#
  # セッション期限延長
  def reset_session_expires
    request.session_options[:expire_after] = 2.weeks
  end

  #--------------#
  # current_account #
  #--------------#
  def current_account
    @current_account ||= Account.where( id: session[:account_id] ).first
  end

  helper_method :current_account

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tables = Settings.tables
    @current_plays = Play.current(Time.now).group_by(&:table_id)
    @current_plays.default = []
  end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  # GET /plays
  # GET /plays.json
  def index
    @plays = Play.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @plays }
    end
  end

  # GET /plays/1
  # GET /plays/1.json
  def show
    @play = Play.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @play }
    end
  end

  # GET /plays/new
  # GET /plays/new.json
  def new
    @play = Play.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @play }
    end
  end

  # GET /plays/1/edit
  def edit
    @play = Play.find(params[:id])
  end

  # POST /plays
  # POST /plays.json
  def create
    @play = Play.new(params[:play])

    respond_to do |format|
      if @play.save
        format.html { redirect_to @play, notice: 'Play was successfully created.' }
        format.json { render json: @play, status: :created, location: @play }
      else
        format.html { render action: "new" }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /plays/1
  # PUT /plays/1.json
  def update
    @play = Play.find(params[:id])

    respond_to do |format|
      if @play.update_attributes(params[:play])
        format.html { redirect_to @play, notice: 'Play was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plays/1
  # DELETE /plays/1.json
  def destroy
    @play = Play.find(params[:id])
    @play.destroy

    respond_to do |format|
      format.html { redirect_to plays_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
# coding: utf-8
class SessionsController < ApplicationController

  #----------#
  # callback #
  #----------#
  def callback
    auth = request.env["omniauth.auth"]
    account = Account.where( provider: auth["provider"], uid: auth["uid"] ).first || Account.create_with_omniauth( auth )
    session[:account_id] = account.id

    redirect_to :root, notice: "ログインしました。"
  end

  #---------#
  # destroy #
  #---------#
  def destroy
    session[:account_id] = nil

    redirect_to :root, notice: "ログアウトしました。"
  end

  #---------#
  # failure #
  #---------#
  def failure
    render text: "<span style='color: red;'>Auth Failure</span>"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/views/home/index.html.erb
<h1>Welcome to Snooker Club.</h1>
<h2>テーブル使用状況</h2>
<dl>
  <% @tables.each do |table| %>
    <dt>Table <%= table.id %></dt>
    <% if @current_plays[table.id].present? %>
      <% @current_plays[table.id].each do |play| %>
        <dd><%= play.username %></dd>
      <% end %>
    <% else %>
      <dd>利用可</dd>
    <% end %>
  <% end %>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Snooker Club" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/apple-touch-icon-144x144-precomposed.png">
    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/apple-touch-icon-114x114-precomposed.png">
    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/apple-touch-icon-72x72-precomposed.png">
    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <link rel="apple-touch-icon-precomposed" href="images/apple-touch-icon-precomposed.png">
    <!-- Size should be 32 x 32 pixels -->
    <link href="images/favicon.ico" rel="shortcut icon">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Snooker Club</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li>
                <% if current_account %>
                  <%= link_to_unless( current_account.screen_name.blank?, image_tag( current_account.image, size: "20x20" ), "https://twitter.com/#!/#{current_account.screen_name}", target: "_blank" ) %>
                  <%= current_account.name %> :
                   || <%= link_to "Logout", logout_path %>
                <% else %>
                  <%= link_to "Login", "/auth/facebook" %>
                <% end %>
              </li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>
          Developed by <a href="https://twitter.com/tkawa" target="_blank">tkawa</a>, Designed by <a href="https://twitter.com/" target="_blank">???</a>
        </p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/plays/_form.html.erb
<%= form_for @play, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :table_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :table_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :starts_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :starts_at, :class => 'datetime_select' %>
    </div>
  </div>
<!--
  <div class="control-group">
    <%= f.label :ends_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :ends_at, :class => 'datetime_select' %>
    </div>
  </div>
-->
  <div class="control-group">
    <%= f.label :note, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :note, :class => 'text_area' %>
    </div>
  </div>
<!--
  <div class="control-group">
    <%= f.label :account_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :account_id, :class => 'number_field' %>
    </div>
  </div>
-->

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                plays_path, :class => 'btn' %>
  </div>
<% end %>

app/views/plays/edit.html.erb
<%- model_class = Play -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/plays/index.html.erb
<%- model_class = Play -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:table_id) %></th>
      <th><%= model_class.human_attribute_name(:starts_at) %></th>
      <th><%= model_class.human_attribute_name(:ends_at) %></th>
      <th><%= model_class.human_attribute_name(:note) %></th>
      <th><%= model_class.human_attribute_name(:account_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @plays.each do |play| %>
      <tr>
        <td><%= link_to play.id, play_path(play) %></td>
        <td><%= play.table_id %></td>
        <td><%= play.starts_at %></td>
        <td><%= play.ends_at %></td>
        <td><%= play.note %></td>
        <td><%= play.account_id %></td>
        <td><%=l play.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_play_path(play), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      play_path(play),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_play_path,
            :class => 'btn btn-primary' %>

app/views/plays/new.html.erb
<%- model_class = Play -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/plays/show.html.erb
<%- model_class = Play -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:table_id) %>:</strong></dt>
  <dd><%= @play.table_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:starts_at) %>:</strong></dt>
  <dd><%= @play.starts_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ends_at) %>:</strong></dt>
  <dd><%= @play.ends_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:note) %>:</strong></dt>
  <dd><%= @play.note %></dd>
  <dt><strong><%= model_class.human_attribute_name(:account_id) %>:</strong></dt>
  <dd><%= @play.account_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              plays_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_play_path(@play), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              play_path(@play),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/top/index.html.erb
<h1>Welcome to Snooker Club.</h1>